[package]
name = "cities-states"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = {version = "0.12.1", features = ["image"]}
rand = "0.9.0"
rusqlite = {version = "0.32.0", features = ["bundled"]}